import type { Metadata } from "next";
import Link from "next/link";
const SITE_URL = "https://www.growstackup.com"; const LINKEDIN = "https://www.linkedin.com/in/raza-hussain-niazi-727993206";
export const metadata: Metadata = {
 title: "Raza Hussain Niazi | Founder of GrowStackUp",
 description: "Raza Hussain Niazi is the founder of GrowStackUp, a B2B signal-intelligence and lead-generation business focused on turning company signals into actionable prospecting.",
 alternates: { canonical: `${SITE_URL}/founder` },
 authors: [{name:"Raza Hussain Niazi",url:LINKEDIN}],
};
const jsonLd={"@context":"https://schema.org","@type":"ProfilePage","@id":`${SITE_URL}/founder#profilepage`,"url":`${SITE_URL}/founder`,"name":"Raza Hussain Niazi | Founder of GrowStackUp","mainEntity":{"@type":"Person","@id":`${SITE_URL}/founder/#person`,"name":"Raza Hussain Niazi","jobTitle":"Founder","url":LINKEDIN,"sameAs":[LINKEDIN],"worksFor":{"@id":`${SITE_URL}/#organization`}}};
export default function FounderPage(){return <main>
 <section className="py-16 sm:py-24"><div className="shell"><Link href="/" className="font-mono text-[0.72rem] uppercase tracking-widest text-muted hover:text-ink">← GrowStackUp</Link><div className="mt-12 max-w-4xl"><span className="eyebrow text-muted">Founder</span><h1 className="display-xl mt-6 text-balance">Raza Hussain Niazi</h1><p className="mt-5 font-mono text-[0.78rem] uppercase tracking-[0.14em] text-muted">Founder · GrowStackUp</p><p className="lead mt-8 max-w-[64ch]">I build practical B2B prospecting systems around one simple idea: a company becomes more interesting to a salesperson when something changes. GrowStackUp is built to find those changes, connect them to the right decision-maker and turn them into a reason to start a conversation.</p><div className="mt-9 flex flex-wrap gap-3"><a href={LINKEDIN} rel="me" className="btn btn-primary">View LinkedIn profile ↗</a><a href="/#sample" className="btn btn-ghost">Request a sample pipeline</a></div></div></div></section>
 <section className="border-y border-line bg-paper-2/50 py-16 sm:py-20"><div className="shell grid gap-y-10 lg:grid-cols-12 lg:gap-x-12"><div className="lg:col-span-5"><span className="eyebrow text-muted">What I work on</span><h2 className="display-lg mt-4">Signal-first sales research.</h2></div><div className="lg:col-span-6 lg:col-start-7 space-y-6 text-[1rem] leading-relaxed text-muted"><p><strong className="text-ink">Account research:</strong> finding the company context that matters before the first touch.</p><p><strong className="text-ink">Decision-maker mapping:</strong> getting beyond generic contact lists to the people who own the workflow.</p><p><strong className="text-ink">Buying signals:</strong> using hiring, expansion, technology, leadership and other public events as timing context.</p><p><strong className="text-ink">Automation:</strong> turning repetitive research and follow-up work into workflow-driven digital workers rather than generic chat interfaces.</p></div></div></section>
 <section className="py-16 sm:py-24"><div className="shell max-w-4xl"><span className="eyebrow text-muted">Connect</span><h2 className="display-lg mt-4">The public profile behind the company.</h2><p className="lead mt-5">My LinkedIn profile is where I publish practical notes on B2B sales, lead generation, AI agents, logistics workflows and the systems behind modern outbound.</p><div className="mt-9"><a href={LINKEDIN} rel="me" className="btn btn-accent">Connect on LinkedIn ↗</a></div></div></section>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}} />
 </main>}